[package]
name = "teemasterparser"
version = "0.1.0"
authors = ["Edgar <git@edgarluque.com>"]
edition = "2018"
description = "Parses the data from one day in https://ddnet.tw/stats/master/ to a gnuplot format."
license = "MIT"
keywords = ["teeworlds", "ddnet", "parser"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
